/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HWM14Integration */

#ifndef _Included_HWM14Integration
#define _Included_HWM14Integration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HWM14Integration
 * Method:    getWinds
 * Signature: (IDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_HWM14Integration_getWinds
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
